[project]
name = "jink3d"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.6",
    "opencv-contrib-python-headless>=4.13.0.92",
    "pandas>=3.0.5",
    "pyopengl>=3.1.10",
    "pyopengl-accelerate>=3.1.10",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.14.0",
    "scipy>=1.17.1",
    "tables>=3.11.1",
]
